debootstrap-$(ARCH).tar.gz : Makefile.debootstrap
	sudo debootstrap \
		--arch=$(ARCH) \
		--include ca-certificates,console-setup,cryptsetup-initramfs,initramfs-tools,locales,keyboard-configuration,network-manager,sudo,u-boot-menu \
		bullseye $(SYSIMAGE)
	sudo tar -C $(SYSIMAGE) -cf - . | pigz -9c > $@

